services:
  db:
    container_name: teastream-postgres
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: teastream
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teastream-backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - teastream-backend

volumes:
  postgres_data:
  redis_data:

networks:
  teastream-backend:
